[project]
name = "krate-extension"
version = "0.1.0"
description = "Krate Python sidecar extension"
requires-python = ">=3.10"
dependencies = [
  "docx2pdf>=0.1.8",
  "pikepdf>=9.10.2",
  "pyinstaller>=6.15.0",
]

[tool.uv]
package = false
